### ISSUE TITLE
Sugestão de melhoria: Validar quantidade de parágrafos

### ISSUE THREAD

**Issue by bartier** [izmcm/birolipsum#23]
Atualmente ao colocar valor inválido de parágrafo a página não emite nenhuma mensagem de atenção:
![image](https://user-images.githubusercontent.com/18057391/67823197-e417ff00-faa0-11e9-9a6f-2c7c92ea5d41.png)

Seria legal colocar uma mensagem cômica ou algo do tipo dizendo que não é possível usar parágrafos negativos.

**Comment by izmcm** [comment]
Corrigido no PR #39
