### ISSUE TITLE
Fazer textarea disabled

### ISSUE THREAD

**Issue by RafaelBroseghini** [izmcm/birolipsum#31]
Talvez seja interessante fazer a `textarea` `disabled` para que nao haja possibilidade de aumentar o numero de paragrafos.

**Comment by izmcm** [comment]
Oi @RafaelBroseghini, tu podes dar mais detalhes? Não entendi direito

**Comment by antigui22** [comment]
O que eu entendi, é para que o texto não seja modificado. Inclusive estou até fazendo aqui rs.

**Comment by RafaelBroseghini** [comment]
Desculpa, estava com pressa. Isso mesmo, haha.

**Comment by izmcm** [comment]
Eita, entendi! Valeu pelo toque @RafaelBroseghini. Já que estás fazendo, @antigui22, vou indicar isso na issue e quando quiser, pode mandar um PR ;)
