### ISSUE TITLE
Botão de Tweet some às vezes

### ISSUE THREAD

**Issue by izmcm** [izmcm/birolipsum#45]
O botão de Tweet às vezes não aparece
![image](https://user-images.githubusercontent.com/27749679/67997143-9088eb00-fc31-11e9-86cd-5dd66d3fa112.png)
E às vezes aparece
![image](https://user-images.githubusercontent.com/27749679/67997156-9e3e7080-fc31-11e9-8f78-032d06c3a89d.png)

**Comment by isisbinder** [comment]
P/ mim nunca aparece.
Acredito que lá na função de exibição por timeout (no começo do script.js) deveria estar assim:

`document.getElementById("twitterButtonBase").style.display = 'block';`

Atualmente o _display_ está como _none_.

**Comment by izmcm** [comment]
Oi @isisbinder, a ideia na verdade é que o botão só apareça após gerar um birolipsum. Por isso que ele começa como _none_

**Comment by paesrafael** [comment]
Olá,

Legal a ideia do projeto rs.
Acredito ter um jeito mais simples de fazer o que esta proposto.

Vou enviar uma PR com esse ajuste.
