### ISSUE TITLE
Sugestao: Tirar tweets by Bolsonaro

### ISSUE THREAD

**Issue by RafaelBroseghini** [izmcm/birolipsum#47]
Voces nao acham que embedar TODOS os tweets do bolsonaro no site estaria fazendo mais propaganda dele? 

Acho que seria mais interessante ter uma aba com todos os tweets toscos dele.

Quando entrei no site hoje e vi os tweets embedados pareceu mais propaganda do que qualquer outra coisa.

Grato :)

**Comment by izmcm** [comment]
Eu tive esse mesmo questionamento quando adicionei o PR, @RafaelBroseghini! Quando vi tua issue conversei com @xReee e concordamos que seria melhor tirar mesmo. Valeu pelo toque :)
