### ISSUE TITLE
Sugestão de melhoria: adicionar fontes das citações no DataSet

### ISSUE THREAD

**Issue by bartier** [izmcm/birolipsum#5]
Talvez seria interessante ter uma forma de controlar as fontes das citações no DataSet. Pelo que entendi a ideia do projeto é ter citações válidas do então Sr. Presidente, então por que não ter um DataSet "validado" por si só? =)

Desde já obrigado pela atenção.

**Comment by izmcm** [comment]
Criei um arquivo [source-dataset.txt](https://github.com/izmcm/birolipsum/blob/master/source-dataset.txt) que vai conter todas as fontes de citações que forem adicionadas ao [dataset.txt](https://github.com/izmcm/birolipsum/blob/master/dataset.txt). Valeu pela sugestão, bartier!
